name: test_app
description: A simple command-line application.
version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '>=2.16.0 <3.0.0'


# dependencies:
#

dev_dependencies:
  lints: ^1.0.0
dependencies: 
  html: ^0.15.0
  http: ^0.13.4
  path: ^1.8.0
