symbols = [
    'BTC/USDT',
    'ETH/USDT',
    'ADA/USDT',
    'ATOM/USDT',
    'AVAX/USDT',
    'BCH/USDT',
    'DOT/USDT',
    # 'FIL/USDT',
    # 'IOTA/USDT',
    # 'LTC/USDT',
    # 'NEO/USDT',
    # 'SOL/USDT',
    # 'TRX/USDT',
    # 'VET/USDT',
    # 'XLM/USDT',
    # 'XRP/USDT',
    # 'ZEC/USDT',
    # 'ZRX/USDT',
    # 'BNB/USDT',
]

aths = {
    'BTC/USDT': 69000,
    'ETH/USDT': 4868,
    'ADA/USDT': 3.1,
    'ATOM/USDT': 44.8,
    'AVAX/USDT': 147,
    'BCH/USDT': 1650,
    'DOT/USDT': 55.09,
    'FIL/USDT': 238,
    'IOTA/USDT': 2.67,
    'LTC/USDT': 413.15,
    'NEO/USDT': 141,
    'SOL/USDT': 259.9,
    'TRX/USDT': 0.18,
    'VET/USDT': 0.279,
    'XLM/USDT': 0.798,
    'XRP/USDT': 1.96,
    'ZEC/USDT': 372,
    'ZRX/USDT': 2.4,
    'BNB/USDT': 691.8,
}

# 'reverseNetworks': {
#                     'tronscan.org': 'TRC20',
#                     'etherscan.io': 'ERC20',
#                     'bscscan.com': 'BSC',
#                     'explorer.binance.org': 'BEP2',
#                     'bithomp.com': 'XRP',
#                     'bloks.io': 'EOS',
#                     'stellar.expert': 'XLM',
#                     'blockchair.com/bitcoin': 'BTC',
#                     'blockchair.com/bitcoin-cash': 'BCH',
#                     'blockchair.com/ecash': 'XEC',
#                     'explorer.litecoin.net': 'LTC',
#                     'explorer.avax.network': 'AVAX',
#                     'solscan.io': 'SOL',
#                     'polkadot.subscan.io': 'DOT',
#                     'dashboard.internetcomputer.org': 'ICP',
#                     'explorer.chiliz.com': 'CHZ',
#                     'cardanoscan.io': 'ADA',
#                     'mainnet.theoan.com': 'AION',
#                     'algoexplorer.io': 'ALGO',
#                     'explorer.ambrosus.com': 'AMB',
#                     'viewblock.io/zilliqa': 'ZIL',
#                     'viewblock.io/arweave': 'AR',
#                     'explorer.ark.io': 'ARK',
#                     'atomscan.com': 'ATOM',
#                     'www.mintscan.io': 'CTK',
#                     'explorer.bitcoindiamond.org': 'BCD',
#                     'btgexplorer.com': 'BTG',
#                     'bts.ai': 'BTS',
#                     'explorer.celo.org': 'CELO',
#                     'explorer.nervos.org': 'CKB',
#                     'cerebro.cortexlabs.ai': 'CTXC',
#                     'chainz.cryptoid.info': 'VIA',
#                     'explorer.dcrdata.org': 'DCR',
#                     'digiexplorer.info': 'DGB',
#                     'dock.subscan.io': 'DOCK',
#                     'dogechain.info': 'DOGE',
#                     'explorer.elrond.com': 'EGLD',
#                     'blockscout.com': 'ETC',
#                     'explore-fetchhub.fetch.ai': 'FET',
#                     'filfox.info': 'FIL',
#                     'fio.bloks.io': 'FIO',
#                     'explorer.firo.org': 'FIRO',
#                     'neoscan.io': 'NEO',
#                     'ftmscan.com': 'FTM',
#                     'explorer.gochain.io': 'GO',
#                     'block.gxb.io': 'GXS',
#                     'hash-hash.info': 'HBAR',
#                     'www.hiveblockexplorer.com': 'HIVE',
#                     'explorer.helium.com': 'HNT',
#                     'tracker.icon.foundation': 'ICX',
#                     'www.iostabc.com': 'IOST',
#                     'explorer.iota.org': 'IOTA',
#                     'iotexscan.io': 'IOTX',
#                     'irishub.iobscan.io': 'IRIS',
#                     'kava.mintscan.io': 'KAVA',
#                     'scope.klaytn.com': 'KLAY',
#                     'kmdexplorer.io': 'KMD',
#                     'kusama.subscan.io': 'KSM',
#                     'explorer.lto.network': 'LTO',
#                     'polygonscan.com': 'POLYGON',
#                     'explorer.ont.io': 'ONT',
#                     'minaexplorer.com': 'MINA',
#                     'nanolooker.com': 'NANO',
#                     'explorer.nebulas.io': 'NAS',
#                     'explorer.nbs.plus': 'NBS',
#                     'explorer.nebl.io': 'NEBL',
#                     'nulscan.io': 'NULS',
#                     'nxscan.com': 'NXS',
#                     'explorer.harmony.one': 'ONE',
#                     'explorer.poa.network': 'POA',
#                     'qtum.info': 'QTUM',
#                     'explorer.rsk.co': 'RSK',
#                     'www.oasisscan.com': 'ROSE',
#                     'ravencoin.network': 'RVN',
#                     'sc.tokenview.com': 'SC',
#                     'secretnodes.com': 'SCRT',
#                     'explorer.skycoin.com': 'SKY',
#                     'steemscan.com': 'STEEM',
#                     'explorer.stacks.co': 'STX',
#                     'www.thetascan.io': 'THETA',
#                     'scan.tomochain.com': 'TOMO',
#                     'explore.vechain.org': 'VET',
#                     'explorer.vite.net': 'VITE',
#                     'www.wanscan.org': 'WAN',
#                     'wavesexplorer.com': 'WAVES',
#                     'wax.eosx.io': 'WAXP',
#                     'waltonchain.pro': 'WTC',
#                     'chain.nem.ninja': 'XEM',
#                     'verge-blockchain.info': 'XVG',
#                     'explorer.yoyow.org': 'YOYOW',
#                     'explorer.zcha.in': 'ZEC',
#                     'explorer.zensystem.io': 'ZEN',
#                 },
#                 'impliedNetworks': {
#                     'ETH': {'ERC20': 'ETH'},
#                     'TRX': {'TRC20': 'TRX'},
